### ISSUE TITLE
Reorganizar todo o backend

### ISSUE THREAD

**Issue by felipecaninnovaes** [felipecaninnovaes/nf-rs#18]
- [x] Refatorar toda a estrutura do projeto
   - [x] Desacoplar toda a regra de negocio temporaria da Web-API
   - [x] Desacoplar o SQL para um modulo central
      - [x] Empresas
      - [x] Usuarios
      - [x] Permissions
      - [x] Nfe
        - [x] Delete

- [x] Refatorar e Padronizar o codigo já existente
   - [x] Padronizar todos os Erros da Web-API para que fique semanticamente igual
   - [x] Padronizar todos o SELECT, INSERT, UPDATE, DELETE do projeto
